import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "fr";

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
    en: {
        // Wizard
        "wizard.title": "3-Step Space Planner",
        "wz.eyebrow": "Online Design Platform",
        "wz.title": "3-Step Space Planner",
        "wz.lang": "Language",
        "s1.title": "Step 1: Contact Information",
        "s1.subtitle": "First, let's get your contact information.",
        "s1.name": "Name *",
        "s1.namePh": "Name",
        "s1.email": "Email *",
        "s1.emailPh": "you@example.com",
        "s1.postal": "Postal Code *",
        "s1.postalPh": "H4W2H8 or 07302",
        "s1.phone": "Phone (optional)",
        "s1.phonePh": "1234567890",
        "s1.errName": "Name must be at least 2 letters",
        "s1.errEmail": "Email must contain @ and a valid domain (.com/.ca/.net/.org)",
        "s1.errPhone": "Phone must be exactly 10 digits",
        "s1.errPostal": "Canada: A1A1A1 (e.g. H4W2H8) · USA: 5 digits (e.g. 07302)",
        "s1.continue": "Continue to Measure",
        "s1.verifyTitle": "Verify Email",
        "s1.verifyBody": "To save your progress and continue, please verify your email address:",
        "s1.verifyCta": "Verify Email & Continue",
        "s1.sending": "Sending...",
        "s1.cancel": "Cancel",
        "s1.sentTitle": "Check your email",
        "s1.sentBody1": "We've sent a magic link to",
        "s1.sentBody2": "Click the link in the email to verify your account and continue with your design.",
        "s1.sentBody3": "Once you click the link, this page will reload and you can proceed to the next step.",
        "s1.toastSent": "Verification email sent!",
        "s1.toastErr": "Could not send verification email. Please try again.",
        "s1.verified": "Verified",
        "s1.verifiedHelp": "Your email is verified — you won't need to verify again.",
        "s1.toastVerified": "Email verified!",
        "s1.verifiedModalTitle": "Email Verified!",
        "s1.verifiedModalBody": "has been verified. You're all set — continue to Step 2 to measure your space.",
        "s1.verifiedModalCta": "Continue to Step 2",
        "s2.title": "Step 2: Draw & Measure",
        "s2.subtitle": "For each space, draw the walls, enter measurements, and upload photos.",
        // "s2.yourSpaces": "Your Spaces",
        // "s2.yourSpacesDesc": "Add each space you want to design. You can add multiple.",
        // "s2.spaceNamePh": "Space name *",
        "s2.closet": "Closet",
        "s2.kitchen": "Kitchen",
        "s2.garage": "Garage",
        "s2.addAnother": "Add Another Space",
        "s2.cats": "Closets / Kitchens / Garages",
        "s2.addAbove": "Add a space above to start drawing and measuring it.",
        "s2.unit": "Unit:",
        "s2.ceiling": "Ceiling Height",
        "s2.storage": "Storage priorities",
        "s2.storageHelp": "Tap your 1st and 2nd priority — 1st turns green, 2nd turns yellow, the rest stays red.",
        "s2.hanging": "Hanging",
        "s2.drawers": "Drawers",
        "s2.shelves": "Shelves",
        "s2.uploadTitle": "Upload Photos & Videos",
        "s2.perFile": "per file",
        "s2.totalWord": "total",
        "s2.max": "Max",
        "s2.mb": "MB",
        "s2.browse": "Click to browse or drag & drop",
        "s2.uploadHintA": "Images and videos · up to",
        "s2.mbEach": "MB each",
        "s2.used": "Used:",
        "s2.of": "of",
        "s2.remaining": "Remaining:",
        "s2.notes": "Additional Notes (Optional)",
        "s2.notesPh": "Anything else we should know? Obstacles, sloped ceilings, etc.",
        "s2.review": "Review & Book",
        "s2.back": "Back",
        "s2.tUploading": "Please wait for files to finish uploading",
        "s2.tAddOne": "Please add at least one space",
        "s2.tName": "Please enter a name for all spaces",
        "s2.tCeiling": "Please enter a valid ceiling height for all spaces",
        "s2.tDraw": "Please draw walls or add a shape template for each space",
        "s2.tWalls": "Please fill in all wall measurements",
        "s2.tWallNums": "All wall measurements must be valid positive numbers",
        "s2.tFailUpload": "Failed to upload",
        "s3.title": "Step 3: Review & Book",
        "s3.subtitle": "Pick a time below to book your live design call, then review your information.",
        "s3.schedule": "Schedule Your Live Design Call",
        "s3.scheduled": "Scheduled",
        "s3.summary": "Your Summary",
        "s3.contact": "Contact Information",
        "s3.name": "Name:",
        "s3.email": "Email:",
        "s3.phone": "Phone:",
        "s3.postal": "Postal Code:",
        "s3.spaces": "Spaces",
        "s3.ceiling": "Ceiling:",
        "s3.walls": "Wall Measurements:",
        "s3.perimeter": "Total Perimeter:",
        "s3.area": "Estimated Area:",
        "s3.storage": "Storage Priorities:",
        "s3.notes": "Additional Notes",
        "s3.files": "Uploaded Files",
        "s3.filesCount": "file(s)",
        "s3.payTitle": "Make a Secure Payment",
        "s3.payLead": "Pay your deposit or invoice online",
        "s3.payDesc": "Encrypted checkout powered by Helcim. Opens securely in a new tab.",
        "s3.payNow": "Pay Now",
        "s3.submit": "Submit My Information",
        "s3.submitted": "Submitted",
        "s3.back": "Back",
        "s3.toastOk": "Your submission was received!",
        "s3.toastFail": "Failed to save submission.",

        // Step 1
        "step1.title": "Tell us about you",
        "step1.name": "Name *",
        "step1.namePlaceholder": "John Smith",
        "step1.nameError": "Name must be at least 2 characters",
        "step1.email": "Email *",
        "step1.emailPlaceholder": "john@example.com",
        "step1.emailError": "Enter a valid email (e.g. name@example.com)",
        "step1.phone": "Phone",
        "step1.phonePlaceholder": "5551234567",
        "step1.phoneError": "Phone must be exactly 10 digits",
        "step1.postal": "Postal/ZIP *",
        "step1.postalPlaceholder": "12345 or H4W2H8",
        "step1.postalError": "Enter a valid US or Canadian postal code",

        // Step 2
        "step2.title": "Add your spaces",
        "step2.subtitle": "CLOSETS / KITCHEN / GARAGE",
        "step2.units": "Units",
        "step2.addSpace": "Add space",
        "step2.noSpaces": "No spaces yet. Click",
        "step2.toBegin": "to begin.",
        "step2.spaceDetails": "Space details",
        "step2.spaceName": "Space name *",
        "step2.ceilingHeight": "Ceiling height",
        "step2.activeSpace": "Active space",
        "step2.deleteSpace": "Delete this space",
        "step2.photosTitle": "Photos & videos (optional)",
        "step2.photosDesc": "Photos and videos are optional, but the more info you share, the lower the chance of misfit or design errors.",
        "step2.uploadClick": "Click to upload files",
        "step2.uploadSize": "Images and videos up to 20MB",
        "step2.filesSelected": "file(s) selected",
        "step2.storagePriorities": "Storage priorities",
        "step2.storageTap": "Tap in order of most needed.",
        "step2.hanging": "Hanging",
        "step2.drawers": "Drawers",
        "step2.shelves": "Shelves",
        "step2.additionalNotes": "Additional notes (optional)",
        "step2.notesPlaceholder": "Any special requirements or preferences...",
        "step2.drawingCompleted": "Drawing completed",
        "step2.noDrawing": "No drawing yet",
        "step2.addAtLeastOne": "Please add at least one space",
        "step2.enterName": "Please enter a name for",
        "step2.enterCeiling": "Please enter ceiling height for",
        "step2.fillWalls": "Please fill all wall measurements for",

        // Step 3
        "step3.title": "Schedule Your Free Consultation",
        "step3.subtitle": "Book a convenient time for your design consultation below.",
        "step3.meetingTitle": "Choose Your Meeting Time",
        "step3.meetingScheduled": "Meeting Scheduled Successfully!",
        "step3.meetingDesc": "Your consultation has been booked. You can now submit your design request.",
        "step3.reschedule": "Reschedule Meeting",
        "step3.loadingCalendar": "Loading calendar...",
        "step3.scheduleBefore": "Please schedule a meeting above before submitting your request.",
        "step3.summaryTitle": "Submission Summary",
        "step3.summaryDesc": "Review your details. You can edit any field before submitting.",
        "step3.field": "Field",
        "step3.value": "Value",
        "step3.fullName": "Full Name",
        "step3.email": "Email",
        "step3.phone": "Phone",
        "step3.postalCode": "Postal Code",
        "step3.spaces": "Spaces",
        "step3.spaceDetails": "Space Details",
        "step3.spaceDrawing": "Space Drawing",
        "step3.wallMeasurements": "Wall Measurements",
        "step3.wall": "Wall",
        "step3.totalPerimeter": "Total Perimeter",
        "step3.estimatedArea": "Estimated Area",
        "step3.storagePriorities": "Storage Priorities",
        "step3.files": "Files",
        "step3.notes": "Notes",
        "step3.none": "None",
        "step3.filesUploaded": "file(s) uploaded",
        "step3.spaceCount": "space(s)",
        "step3.submitRequest": "Submit Request",
        "step3.submitting": "Submitting...",
        "step3.changesSaved": "Changes saved",
        "step3.scheduleMeetingFirst": "Please schedule a meeting before submitting",
        "step3.submissionComplete": "Submission complete! Check your email for confirmation.",
        "step3.submissionFailed": "Submission failed. Please try again.",
        "step3.emailFailed": "Submission saved, but email failed to send.",
        "step3.meetingScheduledToast": "Meeting scheduled successfully!",

        // Drawing Canvas
        "canvas.title": "Draw your space layout",
        "canvas.subtitle": "Draw walls BIRDS EYE VIEW or use ROOM TEMPLATES below",
        "canvas.lShape": "L-Shape",
        "canvas.angle": "Angle",
        "canvas.undo": "Undo",
        "canvas.clear": "Clear",
        "canvas.wallsDrawn": "Walls drawn",
        "canvas.drawingMode": "Drawing mode - Click and drag to draw walls",
        "canvas.enterWallLengths": "Enter wall lengths",
        "canvas.totalPerimeter": "Total Perimeter",
        "canvas.estimatedArea": "Estimated Area",
        "canvas.maxWalls": "Maximum {max} walls allowed per space",
        "canvas.nothingToUndo": "Nothing to undo!",
        "canvas.canvasCleared": "Canvas cleared!",
        "canvas.undoSuccess": "Undo successful!",
        "canvas.templateAdded": "template with {count} wall(s) added!",
        "canvas.shapeExists": "A shape already exists. Please clear the canvas to add a new one.",

        // Navigation
        "nav.next": "Next",
        "nav.back": "Back",
    },
    fr: {
        // Wizard
        "wizard.title": "Planificateur Espace 3 Étapes",
        "wz.eyebrow": "Plateforme de conception en ligne",
        "wz.title": "Planificateur d'espace en 3 étapes",
        "wz.lang": "Langue",
        "s1.title": "Étape 1 : Coordonnées",
        "s1.subtitle": "Commençons par vos coordonnées.",
        "s1.name": "Nom *",
        "s1.namePh": "Nom",
        "s1.email": "Courriel *",
        "s1.emailPh": "vous@exemple.com",
        "s1.postal": "Code postal *",
        "s1.postalPh": "H4W2H8 ou 07302",
        "s1.phone": "Téléphone (facultatif)",
        "s1.phonePh": "1234567890",
        "s1.errName": "Le nom doit contenir au moins 2 lettres",
        "s1.errEmail": "Le courriel doit contenir @ et un domaine valide (.com/.ca/.net/.org)",
        "s1.errPhone": "Le téléphone doit contenir exactement 10 chiffres",
        "s1.errPostal": "Canada : A1A1A1 (ex. H4W2H8) · États-Unis : 5 chiffres (ex. 07302)",
        "s1.continue": "Continuer vers les mesures",
        "s1.verifyTitle": "Vérifier le courriel",
        "s1.verifyBody": "Pour enregistrer votre progression et continuer, veuillez vérifier votre adresse courriel :",
        "s1.verifyCta": "Vérifier et continuer",
        "s1.sending": "Envoi...",
        "s1.cancel": "Annuler",
        "s1.sentTitle": "Vérifiez votre courriel",
        "s1.sentBody1": "Nous avons envoyé un lien magique à",
        "s1.sentBody2": "Cliquez sur le lien dans le courriel pour vérifier votre compte et poursuivre votre conception.",
        "s1.sentBody3": "Une fois le lien cliqué, cette page se rechargera et vous pourrez passer à l'étape suivante.",
        "s1.toastSent": "Courriel de vérification envoyé !",
        "s1.toastErr": "Impossible d'envoyer le courriel de vérification. Veuillez réessayer.",
        "s1.verified": "Vérifié",
        "s1.verifiedHelp": "Votre courriel est vérifié — vous n'aurez pas à le vérifier à nouveau.",
        "s1.toastVerified": "Courriel vérifié !",
        "s1.verifiedModalTitle": "Courriel vérifié !",
        "s1.verifiedModalBody": "a été vérifié. Tout est prêt — passez à l'étape 2 pour mesurer votre espace.",
        "s1.verifiedModalCta": "Passer à l'étape 2",
        "s2.title": "Étape 2 : Dessiner et mesurer",
        "s2.subtitle": "Pour chaque espace, dessinez les murs, entrez les mesures et téléversez des photos.",
        "s2.yourSpaces": "Vos espaces",
        "s2.yourSpacesDesc": "Ajoutez chaque espace à concevoir. Vous pouvez en ajouter plusieurs.",
        "s2.spaceNamePh": "Nom de l'espace *",
        "s2.closet": "Garde-robe",
        "s2.kitchen": "Cuisine",
        "s2.garage": "Garage",
        "s2.addAnother": "Ajouter un autre espace",
        "s2.cats": "Garde-robes / Cuisines / Garages",
        "s2.addAbove": "Ajoutez un espace ci-dessus pour commencer à le dessiner et le mesurer.",
        "s2.unit": "Unité :",
        "s2.ceiling": "Hauteur sous plafond",
        "s2.storage": "Priorités de rangement",
        "s2.storageHelp": "Appuyez sur votre 1re et 2e priorité — la 1re devient verte, la 2e jaune, le reste reste rouge.",
        "s2.hanging": "Penderie",
        "s2.drawers": "Tiroirs",
        "s2.shelves": "Étagères",
        "s2.uploadTitle": "Téléverser photos et vidéos",
        "s2.perFile": "par fichier",
        "s2.totalWord": "au total",
        "s2.max": "Max",
        "s2.mb": "Mo",
        "s2.browse": "Cliquez pour parcourir ou glissez-déposez",
        "s2.uploadHintA": "Images et vidéos · jusqu'à",
        "s2.mbEach": "Mo chacun",
        "s2.used": "Utilisé :",
        "s2.of": "sur",
        "s2.remaining": "Restant :",
        "s2.notes": "Notes supplémentaires (facultatif)",
        "s2.notesPh": "Autre chose à savoir ? Obstacles, plafonds inclinés, etc.",
        "s2.review": "Réviser et réserver",
        "s2.back": "Retour",
        "s2.tUploading": "Veuillez attendre la fin du téléversement des fichiers",
        "s2.tAddOne": "Veuillez ajouter au moins un espace",
        "s2.tName": "Veuillez entrer un nom pour tous les espaces",
        "s2.tCeiling": "Veuillez entrer une hauteur sous plafond valide pour tous les espaces",
        "s2.tDraw": "Veuillez dessiner les murs ou ajouter un modèle pour chaque espace",
        "s2.tWalls": "Veuillez remplir toutes les mesures des murs",
        "s2.tWallNums": "Toutes les mesures des murs doivent être des nombres positifs valides",
        "s2.tFailUpload": "Échec du téléversement",
        "s3.title": "Étape 3 : Réviser et réserver",
        "s3.subtitle": "Choisissez ci-dessous une heure pour réserver votre appel de conception en direct, puis vérifiez vos informations.",
        "s3.schedule": "Planifiez votre appel de conception en direct",
        "s3.scheduled": "Planifié",
        "s3.summary": "Votre résumé",
        "s3.contact": "Coordonnées",
        "s3.name": "Nom :",
        "s3.email": "Courriel :",
        "s3.phone": "Téléphone :",
        "s3.postal": "Code postal :",
        "s3.spaces": "Espaces",
        "s3.ceiling": "Plafond :",
        "s3.walls": "Mesures des murs :",
        "s3.perimeter": "Périmètre total :",
        "s3.area": "Superficie estimée :",
        "s3.storage": "Priorités de rangement :",
        "s3.notes": "Notes supplémentaires",
        "s3.files": "Fichiers téléversés",
        "s3.filesCount": "fichier(s)",
        "s3.payTitle": "Effectuer un paiement sécurisé",
        "s3.payLead": "Payez votre acompte ou facture en ligne",
        "s3.payDesc": "Paiement chiffré propulsé par Helcim. S'ouvre en toute sécurité dans un nouvel onglet.",
        "s3.payNow": "Payer maintenant",
        "s3.submit": "Soumettre mes informations",
        "s3.submitted": "Soumis",
        "s3.back": "Retour",
        "s3.toastOk": "Votre demande a été reçue !",
        "s3.toastFail": "Échec de l'enregistrement de la demande.",

        // Step 1
        "step1.title": "Parlez-nous de vous",
        "step1.name": "Nom *",
        "step1.namePlaceholder": "Jean Dupont",
        "step1.nameError": "Le nom doit contenir au moins 2 caractères",
        "step1.email": "Courriel *",
        "step1.emailPlaceholder": "jean@exemple.com",
        "step1.emailError": "Entrez un courriel valide (ex. nom@exemple.com)",
        "step1.phone": "Téléphone",
        "step1.phonePlaceholder": "5551234567",
        "step1.phoneError": "Le téléphone doit contenir exactement 10 chiffres",
        "step1.postal": "Code postal *",
        "step1.postalPlaceholder": "12345 ou H4W2H8",
        "step1.postalError": "Entrez un code postal valide (Canada ou États-Unis)",

        // Step 2
        "step2.title": "Ajoutez vos espaces",
        "step2.subtitle": "GARDE-ROBES / CUISINE / GARAGE",
        "step2.units": "Unités",
        "step2.addSpace": "Ajouter un espace",
        "step2.noSpaces": "Aucun espace pour l'instant. Cliquez sur",
        "step2.toBegin": "pour commencer.",
        "step2.spaceDetails": "Détails de l'espace",
        "step2.spaceName": "Nom de l'espace *",
        "step2.ceilingHeight": "Hauteur sous plafond",
        "step2.activeSpace": "Espace sélectionné",
        "step2.deleteSpace": "Supprimer cet espace",
        "step2.photosTitle": "Photos et vidéos (facultatif)",
        "step2.photosDesc": "Les photos et vidéos sont facultatives, mais plus vous fournissez de détails, moins il y a de risques d'erreurs de conception.",
        "step2.uploadClick": "Cliquez pour téléverser des fichiers",
        "step2.uploadSize": "Images et vidéos jusqu'à 20 Mo",
        "step2.filesSelected": "fichier(s) sélectionné(s)",
        "step2.storagePriorities": "Priorités de rangement",
        "step2.storageTap": "Appuyez par ordre de priorité.",
        "step2.hanging": "Penderie",
        "step2.drawers": "Tiroirs",
        "step2.shelves": "Étagères",
        "step2.additionalNotes": "Notes supplémentaires (facultatif)",
        "step2.notesPlaceholder": "Exigences ou préférences particulières...",
        "step2.drawingCompleted": "Dessin terminé",
        "step2.noDrawing": "Aucun dessin pour l'instant",
        "step2.addAtLeastOne": "Veuillez ajouter au moins un espace",
        "step2.enterName": "Veuillez entrer un nom pour",
        "step2.enterCeiling": "Veuillez entrer la hauteur sous plafond pour",
        "step2.fillWalls": "Veuillez indiquer toutes les mesures des murs pour",

        // Step 3
        "step3.title": "Planifiez votre consultation gratuite",
        "step3.subtitle": "Réservez ci-dessous le moment qui vous convient pour votre consultation design.",
        "step3.meetingTitle": "Choisissez l'heure de votre rendez-vous",
        "step3.meetingScheduled": "Rendez-vous planifié avec succès !",
        "step3.meetingDesc": "Votre consultation est confirmée. Vous pouvez maintenant soumettre votre demande.",
        "step3.reschedule": "Reporter le rendez-vous",
        "step3.loadingCalendar": "Chargement du calendrier...",
        "step3.scheduleBefore": "Veuillez planifier un rendez-vous ci-dessus avant de soumettre votre demande.",
        "step3.summaryTitle": "Résumé de la demande",
        "step3.summaryDesc": "Vérifiez vos informations. Vous pouvez modifier chaque champ avant de soumettre.",
        "step3.field": "Champ",
        "step3.value": "Valeur",
        "step3.fullName": "Nom complet",
        "step3.email": "Courriel",
        "step3.phone": "Téléphone",
        "step3.postalCode": "Code postal",
        "step3.spaces": "Espaces",
        "step3.spaceDetails": "Détails de l'espace",
        "step3.spaceDrawing": "Plan de l'espace",
        "step3.wallMeasurements": "Mesures des murs",
        "step3.wall": "Mur",
        "step3.totalPerimeter": "Périmètre total",
        "step3.estimatedArea": "Superficie estimée",
        "step3.storagePriorities": "Priorités de rangement",
        "step3.files": "Fichiers",
        "step3.notes": "Notes",
        "step3.none": "Aucun",
        "step3.filesUploaded": "fichier(s) téléversé(s)",
        "step3.spaceCount": "espace(s)",
        "step3.submitRequest": "Soumettre la demande",
        "step3.submitting": "Envoi en cours...",
        "step3.changesSaved": "Modifications enregistrées",
        "step3.scheduleMeetingFirst": "Veuillez planifier un rendez-vous avant de soumettre",
        "step3.submissionComplete": "Demande envoyée ! Vérifiez votre courriel pour la confirmation.",
        "step3.submissionFailed": "L'envoi a échoué. Veuillez réessayer.",
        "step3.emailFailed": "Demande enregistrée, mais l'envoi du courriel a échoué.",
        "step3.meetingScheduledToast": "Rendez-vous planifié avec succès !",

        // Drawing Canvas
        "canvas.title": "Dessinez le plan de votre pièce",
        "canvas.subtitle": "Dessinez les murs en VUE DE DESSUS ou utilisez les MODÈLES DE PIÈCES ci-dessous",
        "canvas.lShape": "Forme en L",
        "canvas.angle": "Angle",
        "canvas.undo": "Annuler",
        "canvas.clear": "Effacer",
        "canvas.wallsDrawn": "Murs dessinés",
        "canvas.drawingMode": "Mode dessin - Cliquez et glissez pour tracer les murs",
        "canvas.enterWallLengths": "Saisissez la longueur des murs",
        "canvas.totalPerimeter": "Périmètre total",
        "canvas.estimatedArea": "Superficie estimée",
        "canvas.maxWalls": "Maximum de {max} murs autorisé par espace",
        "canvas.nothingToUndo": "Rien à annuler !",
        "canvas.canvasCleared": "Plan effacé !",
        "canvas.undoSuccess": "Annulation réussie !",
        "canvas.templateAdded": "modèle de {count} mur(s) ajouté !",
        "canvas.shapeExists": "Une forme existe déjà. Veuillez effacer le canevas pour en ajouter une nouvelle.",

        // Navigation
        "nav.next": "Suivant",
        "nav.back": "Retour",
    },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>(() => {
        const saved = localStorage.getItem("wizardLanguage");
        return (saved === "fr" ? "fr" : "en") as Language;
    });

    const handleSetLanguage = (lang: Language) => {
        setLanguage(lang);
        localStorage.setItem("wizardLanguage", lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within LanguageProvider");
    return context;
};
